version: 2.1
  
jobs:
  build:
    macos:
      xcode: 15.2.0
    
    steps:
      - run:
          command: |
            for i in $(seq 0 1 100000); do
                echo $i; sleep 5
            done

workflows:
  say-hello-workflow:
    jobs:
      - build
