version: 2.1
jobs:
  build:
    parameters:
      xcodeversion:
        type: string
    macos:
      xcode: << parameters.xcodeversion >>
    steps:
      - run:
          command: /Library/Application\ Support/VMware\ Tools/vmware-tools-cli -v

workflows:
  check-vmware-versions:
    jobs:
      - build:
          matrix:
            parameters:
              xcodeversion: ["11.6.0", "11.5.0", "11.1.0", "10.3.0"]